import type { Metadata } from "next";
import "../styles/global.css";

export const metadata: Metadata = {
  title: "IT for Green",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  );
}
